- name: Remover
  hosts: docker
  tasks:

  - name: parando apache...
    service:
     name: apache2
     state: stopped

  - name: removendo o apache
    package:
     name:
      - apache2
     state: absent


